#pragma once
#include "tim_format.h"
#include <vector>
#include <string>
#include <optional>

namespace tim {

// Owns every loaded TIM_Image and is the only place allowed to mutate them.
// Centralizing edits here (instead of poking TIM_Image fields from UI code)
// keeps dirty-tracking and future editing features (palette edits, pixel
// edits, etc.) consistent no matter which panel triggers them.
//
// This class stays GL-agnostic on purpose (no #include of anything OpenGL-
// aware, no gfx/ dependency): callers in the UI/gfx layers are responsible
// for keeping TIM_Image::opengl_texture_ids in sync after any edit here
// that changes pixel/CLUT content or count (TIMTextureBuilder::BuildTextures/
// RebuildTextures/DeleteTextures), and for running any image-processing
// algorithm (e.g. gfx::ImageQuantizer) before handing prepared results in.
class Document {
public:
    std::vector<TIM_Image>& Images() { return images; }
    const std::vector<TIM_Image>& Images() const { return images; }

    // Appends newly loaded images; returns the index of the first one
    // added (handy for auto-selecting it), or -1 if none.
    int AddImages(std::vector<TIM_Image>&& new_images);

    // Appends one new, blank 32x32 16bpp direct-color image to `filepath`
    // (VRAM origin (0,0) - see the "new images/CLUTs" convention on
    // SetImageOrigin's callers). Returns its index. The caller must build
    // its GL textures afterward (TIMTextureBuilder::BuildTextures).
    int AddBlankImage(const std::string& filepath);

    int GetActiveIndex() const { return active_index; }
    void SetActiveIndex(int index) { active_index = index; }

    // Moves an image/CLUT block within VRAM, clamped to stay in bounds.
    // No-op (and doesn't dirty the file) if the position doesn't change.
    void SetImageOrigin(int index, int x, int y);
    void SetClutOrigin(int index, int x, int y);

    // Wholesale replacement of an image's encoded pixel/CLUT data (BPP
    // switch, import apply, canvas resize, repacking after a palette edit).
    // `width_words` must already be computed by the caller (e.g.
    // gfx::ImageQuantizer::PixelWidthToWords) - Document doesn't depend on
    // gfx. Leaves master_rgba/master_width/master_index_map untouched, and
    // never touches the CLUT's origin_x/origin_y either way: a CLUT
    // regenerated by a BPP switch/import/repack keeps living wherever this
    // image's CLUT already was (or (0,0), TIM_CLUT_Header's own default, if
    // it never had one) - switching to a direct-color mode and back never
    // loses its old spot. The caller must call
    // TIMTextureBuilder::RebuildTextures afterward - dimensions/CLUT count
    // may have changed.
    struct ImageContent {
        uint8_t type = 0;
        int bpp = 0;
        int pixel_width = 0;
        int width_words = 0;
        int height = 0;
        std::vector<uint8_t> image_data;
        bool has_clut = false;
        int colors_per_clut = 0;
        int num_cluts = 0;
        std::vector<uint16_t> clut_data;
    };
    void ReplaceImageContent(int index, ImageContent&& content);

    // Wholesale replacement of the "highest quality" master edit buffer
    // (import, canvas resize, direct paint strokes). index_map may be left
    // empty (meaningless outside indexed BPP modes).
    struct MasterContent {
        std::vector<uint8_t> rgba;
        int width = 0;
        std::vector<uint8_t> index_map;
    };
    void ReplaceMasterImage(int index, MasterContent&& master);

    // A single paint stroke touches master_rgba/image_data directly and
    // repeatedly (mouse-move granularity) for responsiveness rather than
    // going through ReplaceImageContent/ReplaceMasterImage's full-buffer
    // moves every sample; call this once per live update to mark the file
    // dirty and let VRAMPanel know to rebuild.
    void MarkContentDirty(int index);

    // Undo support for content edits (paint strokes, BPP switches, canvas
    // resize, import, palette color edits) - a deeper stack than the
    // delete/move undo, since painting naturally wants several undo steps.
    // Call once per undoable action (e.g. at the start of a paint stroke,
    // not per pixel) before mutating. Participates in the same Ctrl+Z as
    // PushUndoSnapshot()/DeleteImage via Undo()'s recency comparison.
    void PushContentUndoSnapshot(int index);

    // Appends one more palette row, copied from the last existing row (or
    // black if none), placed immediately below the existing rows - i.e.
    // exactly where they already sit in VRAM, just extending the block's
    // height by one line. Returns false (no-op) if that would push the
    // block past the bottom of VRAM. Caller must call
    // TIMTextureBuilder::RebuildTextures afterward (one texture per row).
    bool AddClutSlot(int index);

    // Removes palette row `slot`. Returns false (no-op) if this CLUT only
    // has one row left. Caller must call TIMTextureBuilder::RebuildTextures
    // afterward.
    bool RemoveClutSlot(int index, int slot);

    // True if this specific image has unsaved changes (see TIM_Image::dirty).
    bool IsImageDirty(int index) const;

    // True if any image belonging to filepath has unsaved changes.
    bool IsFileDirty(const std::string& filepath) const;

    // Removes every image belonging to filepath from the document (e.g. the
    // user closed that file's tab). Returns false if no image had that path.
    bool CloseFile(const std::string& filepath);

    // Removes a single image (the Image Editor's "Delete Image" button).
    // Undoable via the same Ctrl+Z as origin moves (see Undo()). Returns
    // false if index is out of range.
    bool DeleteImage(int index);

    // If a previously-pending deletion was just permanently discarded
    // (superseded by a newer delete, or invalidated by an Add/Close that
    // changed indices) and hasn't been handed off yet, moves it into `out`
    // so the caller can release its GL textures. Returns false if there's
    // nothing to clean up.
    bool TakeDiscardedDelete(TIM_Image& out);

    // Undo support for VRAM origin edits (image/CLUT moves) AND the most
    // recent DeleteImage - whichever happened more recently wins, so
    // Ctrl+Z always undoes "the last thing", regardless of which kind it
    // was. Call PushUndoSnapshot() before starting a move gesture (e.g. a
    // drag); if the gesture turns out to have changed nothing, call
    // DiscardLastUndo() instead of leaving a no-op entry on the stack.
    // The move-undo stack is cleared whenever images are added or removed,
    // since a snapshot's per-index layout no longer applies after that.
    void PushUndoSnapshot();
    void DiscardLastUndo();

    // Undoes whichever of {last move, last delete, last content edit}
    // happened most recently. If a content edit was undone, `content_rebuild_index`
    // is set to that image's index (the caller must call
    // TIMTextureBuilder::RebuildTextures on it - dimensions/CLUT count may
    // have changed); otherwise it's set to -1.
    bool Undo(int& content_rebuild_index);
    bool Undo() { int unused; return Undo(unused); }
    bool CanUndo() const { return !undo_stack.empty() || pending_delete.has_value() || !content_undo_stack.empty(); }

    // Bumped whenever the loaded set or any image/CLUT VRAM origin/content
    // changes. VRAMPanel compares this against its own last-seen value to
    // know when the emulated VRAM needs to be rebuilt from scratch.
    int GetVramVersion() const { return vram_version; }

    // Bumped only when images are added or removed (not on a plain move or
    // content edit). Panels that cache indices into Images() (selection
    // lists, drag state) must reset that cache when this changes, since
    // indices can shift.
    int GetStructureVersion() const { return structure_version; }

    // Re-serializes every image belonging to filepath (in file order) and overwrites it.
    bool Save(const std::string& filepath);

    // Same as Save, but writes to new_filepath and re-points those images at it.
    bool SaveAs(const std::string& filepath, const std::string& new_filepath);

private:
    struct UndoSnapshot {
        std::vector<uint16_t> image_x, image_y, clut_x, clut_y; // parallel to `images`
        std::vector<bool> image_dirty;                          // parallel to `images`
        int seq = 0;
    };
    struct PendingDelete {
        TIM_Image image;
        int original_index = 0;
        int seq = 0;
    };
    struct ContentSnapshot {
        int index = 0;
        uint8_t type = 0;
        int bpp = 0;
        int pixel_width = 0;
        int width_words = 0;
        int height = 0;
        std::vector<uint8_t> image_data;
        bool has_clut = false;
        int colors_per_clut = 0;
        int num_cluts = 0;
        std::vector<uint16_t> clut_data;
        std::vector<uint8_t> master_rgba;
        int master_width = 0;
        std::vector<uint8_t> master_index_map;
        bool dirty = false;
        int seq = 0;
    };

    std::vector<TIM_Image> images;
    int active_index = -1;
    int vram_version = 0;
    int structure_version = 0;
    std::vector<UndoSnapshot> undo_stack;
    std::vector<ContentSnapshot> content_undo_stack;
    int next_action_seq = 0;
    std::optional<PendingDelete> pending_delete;
    std::optional<TIM_Image> discarded_delete;

    std::vector<int> IndicesForFile(const std::string& filepath) const;
    // If a pending delete exists, moves it to `discarded_delete` (for the
    // caller to pick up via TakeDiscardedDelete) and clears the slot -
    // called whenever indices are about to shift out from under it.
    void DiscardPendingDelete();
};

} // namespace tim
